### ISSUE TITLE
Feat: assets register

### ISSUE THREAD

**Issue by yje9802** [Hanaro-OMNM/Hanasset-BE#11]
## Description
유저 자산 정보 입력 받고 불러오기 로직 구현

## Estimated Duration
12/23(월) ~ 12/23(월) [1일]

## Classification
- [x] 기능
- [ ] 버그
- [ ] 기타

## TO-DO
- [x] PUT 유저 자산 정보 입력 받는 로직 구현
- [x] GET 유저 기본 정보 불러오기 로직 구현
- [x] GET 유저 자산 정보 불러오기 로직 구현
