### ISSUE TITLE
Fix: jwt authentication fix

### ISSUE THREAD

**Issue by yje9802** [Hanaro-OMNM/Hanasset-BE#18]
## Description
Request Header에 토큰이 없더라도 서버에서 200 OK를 반환하는 에러가 있어 수정할 예정입니다.
이외에 JwtAuthenticationFilter의 로직을 좀 더 보완하고자 합니다.

## Estimated Duration
12/24(화) ~ 12/25(수) [2일]

## Classification
- [x] 기능
- [x] 버그
- [ ] 기타

## TO-DO
- [ ] 토큰이 없더라도 필터를 거치면 무조건 200 OK 반환하는 에러 수정
- [ ] 리프레시 토큰 재발급 로직 수정
- [ ] 생년월일이 null인 유저 처리
