### ISSUE TITLE
Feat: normal user register

### ISSUE THREAD

**Issue by yje9802** [Hanaro-OMNM/Hanasset-BE#3]
## Description
프로젝트에 Spring Security 설정 적용하여 일반 회원가입(이메일 방식) 기능 구현

## Estimated Duration
12/15(일) ~ 12/16(월) [2일]

## Classification
- [x] 기능
- [ ] 버그
- [ ] 기타

## TO-DO
- [ ] Spring Security 설정 적용
- [ ] 회원가입 로직 구현
- [ ] DB 저장 테스트
